#! /bin/bash

export SOID_PATH="/usr/src/soid"

eval "$(conda shell.bash hook)"
conda activate duckietown
export PYTHONPATH="${PYTHONPATH}:/usr/src/soid/examples/gui/duckietown-soid/learning"
export PYTHONPATH="${PYTHONPATH}:/usr/src/soid/examples/gui/duckietown-soid/src"
conda develop /usr/src/soid/examples/gui/duckietown-soid

if [ "$1" == "-c" ]
then
   python /usr/src/soid/examples/gui/duckietown-soid/agents/experiment2.py /usr/src/soid/examples/gui/duckietown-soid/configs/example.ini
else
   python /usr/src/soid/examples/gui/duckietown-soid/agents/experiment1.py /usr/src/soid/examples/gui/duckietown-soid/configs/example.ini
fi
